addons:
  apt:
    packages:
    - libgmp-dev
env: JRUBY_OPTS=--debug RAKE_TASK=spec
cache: bundler
language: ruby
matrix:
  include:
    - env: RAKE_TASK=rubocop
      rvm: '2.6.0'
rvm:
  - '2.7'
  - '2.6'
  - '2.5'
  - '2.4'
script: bundle exec rake $RAKE_TASK
sudo: false
